<!DOCTYPE html>

<section>
    <form action = "" method = "post">
        <h3>Inscrivez-vous à la newsletter</h3>
        <input type="email" placeholder="votre adresse mail" required>
        <a href="https://fr-fr.facebook.com/">
            <i class="fa-brands fa-facebook"></i>
        </a>
        <i class="fa-brands fa-instagram">
            <a href="https://www.instagram.com/?hl=fr">

            </i>
        <a href="https://twitter.com/">
            <i class="fa-brands fa-twitter"></i>
        </a>
    </form>
</section>  