<!DOCTYPE html>
<html lang="fr">


<ul>
    <li>
        <a href="index.php?road=articles">Les Articles</a>
    </li>
    <li>
        <a href="index.php?road=artistes" class="active">Les Artistes</a>
    </li>
    <li>
        <a href="index.php?road=addArticles">Ajouter un article</a>
    </li>
    <li>
        <a href="index.php?road=users">Liste des utilisateurs</a>
    </li>
    <li>
        <a href="index.php?road=basket" class="active">Panier</a>
    </li>
    <li>
        <a href="index.php?road=signIn" class="active">Connexion</a>
    </li>
</ul>