<!DOCTYPE html>
<html lang="fr">

<section class="intro">
	<h1>Tous nos articles</h1>
	<a href="index.php?road=albums">Nos albums</a>
	<a href="index.php?road=vinyles">Nos vinyles</a>
</section>
<section>
	<?php foreach($articles as $article): ?>
    <article>
		
		<h2 class="product_name"><?= htmlspecialchars($article['product_name']) ?></h2>
		<p><?= htmlspecialchars($article['artist_name']) ?></p>
		<p>prix: <?= htmlspecialchars($article['price']) ?>€</p>
		<p>catégorie: <?= htmlspecialchars($article['category_name']) ?></p>
		<p>numéro de référence: <?= htmlspecialchars($article['product_id']) ?></p>
		<p>quantité en stock: <?= htmlspecialchars($article['quantity']) ?></p>
		<p>ajouté le: <?= htmlspecialchars($article['created_at']) ?></p>
		<p>modifié le: <?= htmlspecialchars($article['modified_at']) ?></p>

	</article>
	<?php endforeach; ?>
</section>