<!DOCTYPE html>
<html lang="fr">

<head>
<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="description" content="Votre magasin en ligne de K-Pop">
	<title>URPOP</title>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0/css/fontawesome.min.css">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0/css/brands.min.css">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0/css/solid.min.css">
	<link rel="stylesheet" href="public/css/style.css">
</head>

<body>
	<header>
		<div class="nav">
			<span class="nav">
				<a href="index.php?route=home" class="logo">
					<img src="public/img/logo.png" alt="Logo" id="logo">
				</a>
			</span>
			<p>Back Office</p>
			<nav>
				<div class="blocSearch">
					<form action = "" method = "get">
						<input type="search" id="search" autocomplete="off" placeholder="Rechercher un article">
						<input type = "submit" value = "Search">
						<div id="targetLabels"></div>
					</form>
					<?php require_once('_ulNav.phtml'); ?>
				</div>	
			</nav>
		</div>
	</header>

	<main class="container">
		<?php include $template ?>
	</main>

	<footer class="nav">

			<?php require_once('views/_footer.phtml'); ?>
	
	</footer>
</body>

</html>