<!DOCTYPE html>
<html lang="fr">

<head>
<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="description" content="Votre magasin en ligne de K-Pop">
	<title>URPOP</title>
	<link rel="stylesheet" href="public/css/style.css">
</head>

<body>
	<main class="container">
		<h1>Liste des utilisateurs</h1>

		<?php foreach($users as $user): ?>
			<ul>
				<li><?= $user['id'] ?></li>
				<li><?= $user['first_name'] ?></li>
				<li><?= $user['last_name'] ?></li>
				<li><?= $user['email'] ?></li>
				<li><?= $user['password'] ?></li>
			</ul>
        <?php endforeach; ?>
	</main>
</body>

</html>